"""Notifications: generated by the claims flow, read through the bell endpoints."""

from __future__ import annotations

from fastapi.testclient import TestClient

from app.models import NotificationType
from app.services import notification_service
from tests.conftest import ApiUser, create_listing, register_user

NOTIFICATIONS = "/api/v1/notifications"
LISTINGS = "/api/v1/listings"
CLAIMS = "/api/v1/claims"


def bell(user: ApiUser, **params: object) -> dict:
    response = user.client.get(NOTIFICATIONS, params=params, headers=user.headers)
    assert response.status_code == 200, response.text
    return response.json()


def test_claiming_notifies_the_owner(owner: ApiUser, claimer: ApiUser) -> None:
    listing = create_listing(owner)
    claimer.client.post(
        f"{LISTINGS}/{listing['id']}/claims",
        json={"message": "Is it still available?"},
        headers=claimer.headers,
    )

    body = bell(owner)
    assert body["unread_count"] == 1
    notification = body["items"][0]
    assert notification["type"] == "claim_received"
    assert notification["read"] is False
    assert notification["payload"]["listing_id"] == listing["id"]
    assert notification["payload"]["listing_title"] == listing["title"]
    assert notification["payload"]["claimer_display_name"] == claimer.display_name
    assert notification["payload"]["message"] == "Is it still available?"

    # The claimer is not notified of their own action.
    assert bell(claimer)["unread_count"] == 0


def test_accepting_notifies_the_claimer(owner: ApiUser, claimer: ApiUser) -> None:
    listing = create_listing(owner)
    claim = claimer.client.post(
        f"{LISTINGS}/{listing['id']}/claims", json={"message": "yes please"},
        headers=claimer.headers,
    ).json()
    owner.client.patch(
        f"{CLAIMS}/{claim['id']}", json={"action": "accept"}, headers=owner.headers
    )

    body = bell(claimer)
    assert body["unread_count"] == 1
    notification = body["items"][0]
    assert notification["type"] == "claim_accepted"
    assert notification["payload"]["owner_display_name"] == owner.display_name
    assert notification["payload"]["pickup_area"] == listing["pickup_area"]
    assert notification["payload"]["claim_id"] == claim["id"]


def test_declining_does_not_notify(owner: ApiUser, claimer: ApiUser) -> None:
    listing = create_listing(owner)
    claim = claimer.client.post(
        f"{LISTINGS}/{listing['id']}/claims", json={"message": "hi"}, headers=claimer.headers
    ).json()
    owner.client.patch(
        f"{CLAIMS}/{claim['id']}", json={"action": "decline"}, headers=owner.headers
    )
    assert bell(claimer)["unread_count"] == 0


def test_mark_read_decrements_the_badge(owner: ApiUser, claimer: ApiUser) -> None:
    listing = create_listing(owner)
    claimer.client.post(
        f"{LISTINGS}/{listing['id']}/claims", json={"message": "hi"}, headers=claimer.headers
    )
    notification_id = bell(owner)["items"][0]["id"]

    response = owner.client.patch(
        f"{NOTIFICATIONS}/{notification_id}/read", headers=owner.headers
    )
    assert response.status_code == 200
    assert response.json()["read"] is True
    assert bell(owner)["unread_count"] == 0
    # Read notifications stay in the list.
    assert len(bell(owner)["items"]) == 1


def test_mark_read_is_idempotent(owner: ApiUser, claimer: ApiUser) -> None:
    listing = create_listing(owner)
    claimer.client.post(
        f"{LISTINGS}/{listing['id']}/claims", json={"message": "hi"}, headers=claimer.headers
    )
    notification_id = bell(owner)["items"][0]["id"]
    for _ in range(2):
        response = owner.client.patch(
            f"{NOTIFICATIONS}/{notification_id}/read", headers=owner.headers
        )
        assert response.status_code == 200 and response.json()["read"] is True


def test_cannot_read_another_users_notification(
    owner: ApiUser, claimer: ApiUser, client: TestClient
) -> None:
    listing = create_listing(owner)
    claimer.client.post(
        f"{LISTINGS}/{listing['id']}/claims", json={"message": "hi"}, headers=claimer.headers
    )
    notification_id = bell(owner)["items"][0]["id"]
    response = claimer.client.patch(
        f"{NOTIFICATIONS}/{notification_id}/read", headers=claimer.headers
    )
    assert response.status_code == 404
    assert bell(owner)["unread_count"] == 1


def test_notifications_are_scoped_to_the_caller(owner: ApiUser, claimer: ApiUser) -> None:
    listing = create_listing(owner)
    claimer.client.post(
        f"{LISTINGS}/{listing['id']}/claims", json={"message": "hi"}, headers=claimer.headers
    )
    assert len(bell(owner)["items"]) == 1
    assert len(bell(claimer)["items"]) == 0


def test_unread_only_filter(owner: ApiUser, claimer: ApiUser, client: TestClient) -> None:
    second = register_user(client, email="second-claimer@concordia.ca")
    first_listing = create_listing(owner, title="Desk")
    second_listing = create_listing(owner, title="Lamp")
    for user, listing in ((claimer, first_listing), (second, second_listing)):
        user.client.post(
            f"{LISTINGS}/{listing['id']}/claims", json={"message": "hi"}, headers=user.headers
        )

    newest = bell(owner)["items"][0]["id"]
    owner.client.patch(f"{NOTIFICATIONS}/{newest}/read", headers=owner.headers)

    assert len(bell(owner)["items"]) == 2
    unread = bell(owner, unread_only=True)
    assert len(unread["items"]) == 1
    assert unread["unread_count"] == 1


def test_pagination(owner: ApiUser, db) -> None:
    from app.models import User

    user = db.get(User, owner.id)
    for index in range(5):
        notification_service.create(
            db,
            user_id=user.id,
            notification_type=NotificationType.WISHLIST_MATCH,
            payload={"n": index},
        )
    body = bell(owner, limit=2, offset=1)
    assert len(body["items"]) == 2
    assert body["unread_count"] == 5  # badge counts everything unread, not just the page


def test_notifications_require_authentication(client: TestClient) -> None:
    assert client.get(NOTIFICATIONS).status_code == 401
    assert client.patch(f"{NOTIFICATIONS}/1/read").status_code == 401


def test_wishlist_match_payload_shape(owner: ApiUser, db) -> None:
    """The matching agent writes through this helper, so pin its payload."""
    from app.models import Listing

    listing = db.get(Listing, create_listing(owner)["id"])
    notification = notification_service.notify_wishlist_match(
        db,
        user_id=owner.id,
        listing=listing,
        wishlist_item_id=42,
        score=0.8123456,
        rationale="'study desk' matches 'table for studying'.",
    )
    assert notification.type == NotificationType.WISHLIST_MATCH
    assert notification.payload == {
        "listing_id": listing.id,
        "listing_title": listing.title,
        "listing_category": "furniture",
        "wishlist_item_id": 42,
        "score": 0.812,
        "rationale": "'study desk' matches 'table for studying'.",
    }
