"""Initial FreeCycle schema

Revision ID: 0001
Revises:
Create Date: 2026-09-18

Hand-written rather than autogenerated so the JSONB/JSON variant and the shared
PostgreSQL enum types are emitted correctly on both PostgreSQL and SQLite.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine import Connection

revision: str = "0001"
down_revision: str | None = None
branch_labels = None
depends_on = None

# name -> allowed values. Mirrors app.models.enums.
ENUMS: dict[str, tuple[str, ...]] = {
    "category": ("furniture", "books", "electronics", "kitchen", "clothing", "other"),
    "condition": ("like_new", "good", "fair", "worn"),
    "listing_status": ("available", "claimed", "completed", "removed"),
    "claim_status": ("pending", "accepted", "declined", "completed"),
    "notification_type": ("wishlist_match", "claim_received", "claim_accepted"),
    "agent_task": ("draft_listing", "moderate_listing", "run_matching", "draft_pickup_message"),
    "agent_run_status": ("succeeded", "failed", "budget_exceeded"),
}


def _is_pg(conn: Connection) -> bool:
    return conn.dialect.name == "postgresql"


def _enum(name: str, conn: Connection) -> sa.types.TypeEngine[str]:
    """Reference an already-created PG type, or a plain VARCHAR-backed enum elsewhere."""
    values = ENUMS[name]
    if _is_pg(conn):
        return postgresql.ENUM(*values, name=name, create_type=False)
    return sa.Enum(*values, name=name)


def _json(conn: Connection) -> sa.types.TypeEngine[object]:
    return postgresql.JSONB() if _is_pg(conn) else sa.JSON()


def upgrade() -> None:
    conn = op.get_bind()

    # Each PG enum type is used by more than one column in some cases (e.g. `category`
    # on both listings and wishlist_items), so create the types once up front and
    # reference them with create_type=False below.
    if _is_pg(conn):
        for name, values in ENUMS.items():
            postgresql.ENUM(*values, name=name).create(conn, checkfirst=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("display_name", sa.String(80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_created_at", "users", ["created_at"])

    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "owner_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("title", sa.String(140), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", _enum("category", conn), nullable=False),
        sa.Column("condition", _enum("condition", conn), nullable=False),
        sa.Column("photos", _json(conn), nullable=False),
        sa.Column("pickup_area", sa.String(160), nullable=False),
        sa.Column("status", _enum("listing_status", conn), nullable=False),
        sa.Column("ai_generated", sa.Boolean(), nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("flag_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_listings_owner_id", "listings", ["owner_id"])
    op.create_index("ix_listings_category", "listings", ["category"])
    op.create_index("ix_listings_status", "listings", ["status"])
    op.create_index("ix_listings_flagged", "listings", ["flagged"])
    op.create_index("ix_listings_created_at", "listings", ["created_at"])

    op.create_table(
        "claims",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "listing_id",
            sa.Integer(),
            sa.ForeignKey("listings.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "claimer_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("status", _enum("claim_status", conn), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("listing_id", "claimer_id", name="uq_claim_listing_claimer"),
    )
    op.create_index("ix_claims_listing_id", "claims", ["listing_id"])
    op.create_index("ix_claims_claimer_id", "claims", ["claimer_id"])
    op.create_index("ix_claims_listing_status", "claims", ["listing_id", "status"])
    op.create_index("ix_claims_created_at", "claims", ["created_at"])

    op.create_table(
        "wishlist_items",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("keywords", sa.String(240), nullable=False),
        sa.Column("category", _enum("category", conn), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_wishlist_items_user_id", "wishlist_items", ["user_id"])
    op.create_index("ix_wishlist_items_created_at", "wishlist_items", ["created_at"])

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("type", _enum("notification_type", conn), nullable=False),
        sa.Column("payload", _json(conn), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"])
    op.create_index("ix_notifications_user_read", "notifications", ["user_id", "read"])
    op.create_index("ix_notifications_created_at", "notifications", ["created_at"])

    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("task", _enum("agent_task", conn), nullable=False),
        sa.Column("status", _enum("agent_run_status", conn), nullable=False),
        sa.Column(
            "listing_id",
            sa.Integer(),
            sa.ForeignKey("listings.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("tool_calls", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_agent_runs_user_id", "agent_runs", ["user_id"])
    op.create_index("ix_agent_runs_user_created", "agent_runs", ["user_id", "created_at"])
    op.create_index("ix_agent_runs_created_at", "agent_runs", ["created_at"])


def downgrade() -> None:
    conn = op.get_bind()
    for table in ("agent_runs", "notifications", "wishlist_items", "claims", "listings", "users"):
        op.drop_table(table)
    if _is_pg(conn):
        for name in ENUMS:
            postgresql.ENUM(name=name).drop(conn, checkfirst=True)
